name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cups-pdf cups-bsd
      - name: Run tests
        run: |
          mkdir -p $HOME/PDF
          lpr -P PDF sample.pdf
          export TERM=linux
          # Ubuntu in CI uses "sample-job_1.pdf"
          watch --no-title --interval .1 --chgexit 'ls -al $HOME/PDF | grep sample'
          unset TERM
          ls -al $HOME/PDF
          